import { supabase } from "@/integrations/supabase/client";
import type { Scene } from "@/lib/blueprint/scene";

// Persistence for production scenes. Deliberately thin — the plan document is
// validated in scene.ts and drawn in planSheet.ts; this file only stores it.
//
// Table access goes through an untyped handle because the generated Supabase
// types are regenerated by Lovable and won't include production_scenes until
// the migration is applied. Everything here degrades to "not migrated yet"
// rather than throwing.

export interface SceneRow {
  id: string;
  user_id: string;
  name: string;
  slug: string;
  book_id: string | null;
  chapter_index: number | null;
  entry_id: string | null;
  plan: Scene;
  created_at: string;
  updated_at?: string;
}

const db = () => supabase.from("production_scenes" as any) as any;

/** True when the scenes table exists (migration applied). */
export async function scenesMigrated(): Promise<boolean> {
  try {
    const { error } = await db().select("id", { head: true, count: "exact" }).limit(1);
    return !error;
  } catch {
    return false;
  }
}

export async function listScenes(limit = 50): Promise<SceneRow[]> {
  const { data } = await db().select("*").order("created_at", { ascending: false }).limit(limit);
  return (data as SceneRow[]) || [];
}

/** Resolve by uuid or by name, case-insensitively. Scene names are unique per
 *  user, so a name is a usable handle the way a master's @name is. */
export async function resolveScene(idOrName: string): Promise<SceneRow | null> {
  const s = String(idOrName || "").trim();
  if (!s) return null;
  if (/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(s)) {
    const { data } = await db().select("*").eq("id", s).maybeSingle();
    return (data as SceneRow) || null;
  }
  const { data } = await db().select("*").ilike("name", s).limit(1);
  const rows = (data as SceneRow[]) || [];
  return rows[0] || null;
}

/** Insert or replace a scene by name. Saving the same scene twice updates it
 *  rather than colliding on the unique index — a plan is revised constantly. */
export async function saveScene(
  plan: Scene,
  opts: { bookId?: string | null; chapterIndex?: number | null } = {},
): Promise<SceneRow> {
  const { data: userData } = await supabase.auth.getUser();
  const uid = userData.user?.id;
  if (!uid) throw new Error("Not signed in");

  const existing = await resolveScene(plan.name);
  const row = {
    user_id: uid,
    name: plan.name,
    slug: plan.slug || "",
    book_id: opts.bookId ?? existing?.book_id ?? null,
    chapter_index: opts.chapterIndex ?? existing?.chapter_index ?? null,
    plan,
    updated_at: new Date().toISOString(),
  };

  if (existing) {
    const { data, error } = await db().update(row).eq("id", existing.id).select("*").maybeSingle();
    if (error) throw new Error(`Scene could not be saved: ${error.message}`);
    return data as SceneRow;
  }
  const { data, error } = await db().insert(row).select("*").single();
  if (error) throw new Error(`Scene could not be saved: ${error.message}`);
  return data as SceneRow;
}

export async function deleteScene(id: string): Promise<void> {
  const { data: deleted, error } = await db().delete().eq("id", id).select("id");
  if (error) throw error;
  if (!deleted || (deleted as any[]).length === 0) {
    throw new Error("Scene could not be deleted (not found or no permission).");
  }
}
