-- =====================================================================
-- Admin dashboard: roles, activity metrics, and privileged RPCs
-- ---------------------------------------------------------------------
-- Security model (2025 Supabase best practice):
--   * Roles live in a dedicated public.user_roles table that NORMAL users
--     cannot write to (no INSERT/UPDATE/DELETE policies). Only the
--     service_role / SECURITY DEFINER functions / a migration (postgres)
--     can mutate it. This avoids privilege escalation and RLS recursion.
--   * Authorization is checked by SECURITY DEFINER helpers (is_admin /
--     has_role) so RLS lookups don't recurse and can't be spoofed by the
--     client. search_path is pinned to '' on every definer function.
--   * Cross-user reads/writes (listing every user, editing someone else's
--     model/API key, deleting a user) happen ONLY inside SECURITY DEFINER
--     RPCs that re-check is_admin() before doing anything. The anon/service
--     key never touches the browser.
-- =====================================================================

-- pgcrypto (crypt / gen_salt) for seeding the admin account password hash
create extension if not exists pgcrypto with schema extensions;

-- ---------------------------------------------------------------------
-- 1. Role enum + table
-- ---------------------------------------------------------------------
do $$
begin
  if not exists (select 1 from pg_type where typname = 'app_role') then
    create type public.app_role as enum ('admin', 'user');
  end if;
end $$;

create table if not exists public.user_roles (
  id         bigint generated by default as identity primary key,
  user_id    uuid not null references auth.users (id) on delete cascade,
  role       public.app_role not null,
  created_at timestamptz not null default now(),
  unique (user_id, role)
);

alter table public.user_roles enable row level security;

-- A user may read their OWN roles; nobody (client-side) may write roles.
drop policy if exists "read own roles" on public.user_roles;
create policy "read own roles"
  on public.user_roles for select to authenticated
  using (auth.uid() = user_id);

-- ---------------------------------------------------------------------
-- 2. Authorization helpers (SECURITY DEFINER, search_path pinned)
-- ---------------------------------------------------------------------
create or replace function public.has_role(_user_id uuid, _role public.app_role)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1 from public.user_roles
    where user_id = _user_id and role = _role
  );
$$;

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1 from public.user_roles
    where user_id = auth.uid() and role = 'admin'::public.app_role
  );
$$;

-- ---------------------------------------------------------------------
-- 3. Per-user activity metrics
-- ---------------------------------------------------------------------
create table if not exists public.activity_events (
  id         bigint generated by default as identity primary key,
  user_id    uuid not null references auth.users (id) on delete cascade,
  event_type text not null default 'visit',
  created_at timestamptz not null default now()
);

create index if not exists activity_events_user_created_idx
  on public.activity_events (user_id, created_at desc);

alter table public.activity_events enable row level security;

-- Users log only their OWN events; only admins can read across users.
drop policy if exists "insert own activity" on public.activity_events;
create policy "insert own activity"
  on public.activity_events for insert to authenticated
  with check (auth.uid() = user_id);

drop policy if exists "admin read activity" on public.activity_events;
create policy "admin read activity"
  on public.activity_events for select to authenticated
  using (public.is_admin());

-- ---------------------------------------------------------------------
-- 4. Admin RPCs (each re-checks is_admin internally)
-- ---------------------------------------------------------------------

-- 4a. List every user with their settings + activity rollup.
create or replace function public.admin_list_users()
returns table (
  id                   uuid,
  email                text,
  created_at           timestamptz,
  last_sign_in_at      timestamptz,
  selected_model       text,
  deep_research_model  text,
  voice_model          text,
  wiki_model           text,
  openrouter_api_key   text,
  inworld_api_key      text,
  burplexity_api_token text,
  is_admin             boolean,
  visits_total         bigint,
  visits_today         bigint,
  last_seen            timestamptz
)
language plpgsql
stable
security definer
set search_path = ''
as $$
begin
  if not public.is_admin() then
    raise exception 'not authorized' using errcode = '42501';
  end if;

  return query
  select
    u.id,
    u.email::text,
    u.created_at,
    u.last_sign_in_at,
    s.selected_model,
    s.deep_research_model,
    s.voice_model,
    s.wiki_model,
    s.openrouter_api_key,
    s.inworld_api_key,
    s.burplexity_api_token,
    public.has_role(u.id, 'admin'::public.app_role) as is_admin,
    coalesce(a.visits_total, 0) as visits_total,
    coalesce(a.visits_today, 0) as visits_today,
    a.last_seen
  from auth.users u
  left join public.user_settings s on s.user_id = u.id
  left join lateral (
    select
      count(*) as visits_total,
      count(*) filter (where e.created_at >= date_trunc('day', now())) as visits_today,
      max(e.created_at) as last_seen
    from public.activity_events e
    where e.user_id = u.id
  ) a on true
  order by u.created_at desc;
end;
$$;

-- 4b. Set another user's models / API keys. NULL = leave unchanged.
create or replace function public.admin_update_user_settings(
  _user_id              uuid,
  _selected_model       text default null,
  _deep_research_model  text default null,
  _voice_model          text default null,
  _wiki_model           text default null,
  _openrouter_api_key   text default null,
  _inworld_api_key      text default null,
  _burplexity_api_token text default null
)
returns void
language plpgsql
security definer
set search_path = ''
as $$
begin
  if not public.is_admin() then
    raise exception 'not authorized' using errcode = '42501';
  end if;

  -- Ensure a settings row exists for the target user.
  insert into public.user_settings (user_id)
  values (_user_id)
  on conflict (user_id) do nothing;

  update public.user_settings set
    selected_model       = coalesce(_selected_model,       selected_model),
    deep_research_model  = coalesce(_deep_research_model,  deep_research_model),
    voice_model          = coalesce(_voice_model,          voice_model),
    wiki_model           = coalesce(_wiki_model,           wiki_model),
    openrouter_api_key   = coalesce(_openrouter_api_key,   openrouter_api_key),
    inworld_api_key      = coalesce(_inworld_api_key,      inworld_api_key),
    burplexity_api_token = coalesce(_burplexity_api_token, burplexity_api_token),
    updated_at           = now()
  where user_id = _user_id;

  -- Keep the chosen model visible in the user's saved-models dropdown.
  if _selected_model is not null and length(_selected_model) > 0 then
    update public.user_settings set
      saved_models = case
        when coalesce(saved_models, '[]'::jsonb) ? _selected_model then saved_models
        else coalesce(saved_models, '[]'::jsonb) || to_jsonb(_selected_model)
      end
    where user_id = _user_id;
  end if;
end;
$$;

-- 4c. Delete a user (cascades to all their data). Guards against deleting
--     yourself or another admin.
create or replace function public.admin_delete_user(_user_id uuid)
returns void
language plpgsql
security definer
set search_path = ''
as $$
begin
  if not public.is_admin() then
    raise exception 'not authorized' using errcode = '42501';
  end if;
  if _user_id = auth.uid() then
    raise exception 'you cannot delete your own admin account';
  end if;
  if public.has_role(_user_id, 'admin'::public.app_role) then
    raise exception 'cannot delete another admin account';
  end if;

  delete from auth.users where id = _user_id;
end;
$$;

-- 4d. Per-user daily visit counts for the metrics chart.
create or replace function public.admin_user_daily_visits(_user_id uuid, _days int default 30)
returns table (day date, visits bigint)
language plpgsql
stable
security definer
set search_path = ''
as $$
begin
  if not public.is_admin() then
    raise exception 'not authorized' using errcode = '42501';
  end if;

  return query
  select (date_trunc('day', e.created_at))::date as day, count(*)::bigint as visits
  from public.activity_events e
  where e.user_id = _user_id
    and e.created_at >= now() - make_interval(days => greatest(_days, 1))
  group by 1
  order by 1;
end;
$$;

-- Allow signed-in users to call these RPCs (each enforces is_admin internally).
grant execute on function public.is_admin() to authenticated;
grant execute on function public.has_role(uuid, public.app_role) to authenticated;
grant execute on function public.admin_list_users() to authenticated;
grant execute on function public.admin_update_user_settings(uuid, text, text, text, text, text, text, text) to authenticated;
grant execute on function public.admin_delete_user(uuid) to authenticated;
grant execute on function public.admin_user_daily_visits(uuid, int) to authenticated;

-- ---------------------------------------------------------------------
-- 5. Backup: auto-grant admin role if the admin account ever signs up
--    through the normal flow (in case the seed below is skipped).
-- ---------------------------------------------------------------------
create or replace function public.grant_admin_on_signup()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  if new.email = 'bvprivate@admin.local' then
    insert into public.user_roles (user_id, role)
    values (new.id, 'admin'::public.app_role)
    on conflict (user_id, role) do nothing;
  end if;
  return new;
end;
$$;

drop trigger if exists grant_admin_on_signup_trg on auth.users;
create trigger grant_admin_on_signup_trg
  after insert on auth.users
  for each row execute function public.grant_admin_on_signup();

-- ---------------------------------------------------------------------
-- 6. Seed the dedicated admin account.
--    Username "bvprivate" maps to email bvprivate@admin.local in the UI.
--    Password: Moop179205  (change it later via Supabase Auth if desired).
--    Wrapped in exception handlers so a schema quirk can never abort the
--    whole migration; the trigger above is the fallback path.
-- ---------------------------------------------------------------------
do $$
declare
  v_uid   uuid;
  v_email text := 'bvprivate@admin.local';
  v_pass  text := 'Moop179205';
begin
  select id into v_uid from auth.users where email = v_email;

  if v_uid is null then
    begin
      v_uid := gen_random_uuid();

      insert into auth.users (
        instance_id, id, aud, role, email, encrypted_password,
        email_confirmed_at, created_at, updated_at,
        raw_app_meta_data, raw_user_meta_data,
        confirmation_token, recovery_token, email_change, email_change_token_new
      ) values (
        '00000000-0000-0000-0000-000000000000',
        v_uid, 'authenticated', 'authenticated', v_email,
        extensions.crypt(v_pass, extensions.gen_salt('bf')),
        now(), now(), now(),
        '{"provider":"email","providers":["email"]}'::jsonb,
        '{}'::jsonb,
        '', '', '', ''
      );

      begin
        insert into auth.identities (
          provider_id, user_id, identity_data, provider,
          last_sign_in_at, created_at, updated_at
        ) values (
          v_uid::text, v_uid,
          jsonb_build_object('sub', v_uid::text, 'email', v_email),
          'email', now(), now(), now()
        );
      exception when others then
        raise notice 'admin identity seed skipped: %', sqlerrm;
      end;
    exception when others then
      raise notice 'admin user seed skipped: %', sqlerrm;
      v_uid := null;
    end;
  end if;

  if v_uid is not null then
    insert into public.user_roles (user_id, role)
    values (v_uid, 'admin'::public.app_role)
    on conflict (user_id, role) do nothing;
  end if;
end $$;
